SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

INSERT INTO `categories` (`categoryId`, `facebookName`, `prettyName`) VALUES
(3, 'Tv show', 'TV Shows'),
(2, 'Movie', 'Movies'),
(1, 'Musician/band', 'Bands'),
(4, 'Professional sports team', 'Sports'),
(5, 'Interest', 'Interests'),
(6, 'Fictional character', 'Fictional characters'),
(7, 'School', 'Schools'),
(8, 'Concert tour', 'Concert tours'),
(9, 'Entertainment', 'Entertainment'),
(10, 'University', 'Universities'),
(11, 'Movie general', 'Movies'),
(12, 'Book', 'Books'),
(13, 'Field of study', 'Fields of study'),
(14, 'Organization', 'Organizations'),
(15, 'Community', 'Communities'),
(16, 'Author', 'Authors'),
(17, 'Concert venue', 'Concert venues'),
(18, 'Software', 'Software'),
(19, 'Entertainer', 'Entertainers'),
(20, 'Wine/spirits', 'Wine/spirits'),
(21, 'Public figure', 'Public figures'),
(22, 'Shopping/retail', 'Shopping stores'),
(23, 'Bar', 'Bars'),
(24, 'Education', 'Education'),
(25, 'Product/service', 'Products or services'),
(26, 'Company', 'Companies'),
(27, 'Sports league', 'Sports leagues'),
(28, 'Restaurant/cafe', 'Restaurants'),
(29, 'Sport', 'Sports'),
(30, 'Computers/technology', 'Computers/technology'),
(31, 'Computers', 'Computers'),
(32, 'Professional services', 'Professional services'),
(33, 'Games/toys', 'Games or toys'),
(34, 'Attractions/things to do', 'Attractions'),
(35, 'Local business', 'Local businesses'),
(36, 'Website', 'Websites'),
(37, 'Food/beverages', 'Food/beverages'),
(38, 'Non-profit organization', 'Non-profit organizations'),
(39, 'Food/grocery', 'Food/groceries'),
(40, 'Sports/recreation/activities', 'Sports/recreation/activities'),
(41, 'Cause', 'Causes'),
(42, 'Application', 'Applications'),
(43, 'Dancer', 'Dancers'),
(44, 'Retail and consumer merchandise', 'Merchandise'),
(45, 'Music', 'Music'),
(46, 'Outdoor gear/sporting goods', 'Outdoor gear/sporting goods'),
(47, 'Athlete', 'Athletes'),
(48, 'Comedian', 'Comedians'),
(49, 'Album', 'Albums'),
(50, 'Actor/director', 'Actor/director'),
(51, 'School sports team', 'School sports teams'),
(52, 'Real estate', 'Real estate'),
(53, 'Radio station', 'Radio stations'),
(54, 'Clothing', 'Clothes'),
(55, 'Political organization', 'Political organizations'),
(56, 'Movies/music', 'Movies/musics'),
(57, 'Health/medical/pharmaceuticals', 'Health/medical/pharmaceuticals'),
(58, 'Health/wellness', 'Health/wellness'),
(59, 'Politician', 'Politicians'),
(60, 'Arts/entertainment/nightlife', 'Arts/entertainment/nightlife'),
(61, 'Small business', 'Small business'),
(62, 'Internet/software', 'Internet/software'),
(63, 'Pet services', 'Pet services'),
(64, 'Event planning/event services', 'Event planning/event services'),
(65, 'Insurance company', 'Insurance company'),
(66, 'News/media', 'News/media'),
(67, 'App', 'App'),
(68, 'Arts/humanities', 'Arts/humanities'),
(69, 'Artist', 'Artist'),
(70, 'Personal blog', 'Personal blog'),
(71, 'Landmark', 'Landmark'),
(72, 'Diseases', 'Diseases'),
(73, 'Health/medical/pharmacy', 'Health/medical/pharmacy'),
(74, 'Journalist', 'Journalist'),
(75, 'Camera/photo', 'Camera/photo'),
(76, 'Government official', 'Government official'),
(77, 'Household supplies', 'Household supplies'),
(78, 'Museum/art gallery', 'Museum/art gallery'),
(79, 'Producer', 'Producer'),
(80, 'Computers/internet', 'Computers/internet'),
(81, 'Travel/leisure', 'Travel/leisure'),
(82, 'Club', 'Club'),
(83, 'Media/news/publishing', 'Media/news/publishing'),
(84, 'Teacher', 'Teacher'),
(85, 'Writer', 'Writer'),
(86, 'Tv', 'Tv'),
(87, 'Appliances', 'Appliances'),
(88, 'Reference', 'Reference'),
(89, 'Hotel', 'Hotel'),
(90, 'Record label', 'Record label'),
(91, 'Government organization', 'Government organization'),
(92, 'Tv network', 'Tv network'),
(93, 'Church/religious organization', 'Church/religious organization'),
(94, 'Consulting/business services', 'Consulting/business services'),
(95, 'Song', 'Song'),
(96, 'Society/culture', 'Society/culture'),
(97, 'Business person', 'Business person'),
(98, 'Tv channel', 'Tv channel'),
(99, 'Cars', 'Cars'),
(100, 'Magazine', 'Magazine'),
(101, 'Local/travel', 'Local/travel'),
(102, 'Animal', 'Animal'),
(103, 'Telecommunication', 'Telecommunication'),
(104, 'Movie genre', 'Movie genre'),
(105, 'Musical genre', 'Musical genre'),
(106, 'Musical instrument', 'Musical instrument'),
(107, 'Coach', 'Coach'),
(108, 'Recreation/sports', 'Recreation/sports'),
(109, 'Business services', 'Business services'),
(110, 'Unknown', 'Unknown'),
(111, 'Home decor', 'Home decor'),
(112, 'Home improvement', 'Home improvement'),
(113, 'City', 'City'),
(114, 'Book store', 'Book store'),
(115, 'Video', 'Video'),
(116, 'Automotive', 'Automotive'),
(117, 'Health/beauty', 'Health/beauty'),
(118, 'Bank/financial institution', 'Bank/financial institution'),
(119, 'Studio', 'Studio'),
(120, 'Religion', 'Religion'),
(121, 'Music chart', 'Music chart'),
(122, 'Public places', 'Public places'),
(123, 'Community/government', 'Community/government'),
(124, 'Legal/law', 'Legal/law'),
(125, 'Book genre', 'Book genre'),
(126, 'Animal breed', 'Animal breed'),
(127, 'Episode', 'Episode'),
(128, 'Community organization', 'Community organization'),
(129, 'Vitamins/supplements', 'Vitamins/supplements'),
(130, 'Food', 'Food'),
(131, 'Movie theater', 'Movie theater'),
(132, 'Furniture', 'Furniture'),
(133, 'Political party', 'Political party'),
(134, 'Work position', 'Work position'),
(135, 'Spas/beauty/personal care', 'Spas/beauty/personal care'),
(136, 'Business/economy', 'Business/economy'),
(137, 'Library', 'Library'),
(138, 'Home/garden', 'Home/garden'),
(139, 'Tours/sightseeing', 'Tours/sightseeing'),
(140, 'Transportation', 'Transportation'),
(141, 'Electronics', 'Electronics'),
(142, 'Music video', 'Music video'),
(143, 'Airport', 'Airport'),
(144, '', ''),
(145, 'Science', 'Science'),
(146, 'Chef', 'Chef'),
(147, 'Non-governmental organization (ngo)', 'Non-governmental organization (ngo)'),
(148, 'Publisher', 'Publisher'),
(149, 'Personal website', 'Personal website'),
(150, 'Tools/equipment', 'Tools/equipment'),
(151, 'Editor', 'Editor'),
(152, 'Monarch', 'Monarch'),
(153, 'Teens/kids', 'Teens/kids'),
(154, 'Amateur sports team', 'Amateur sports team'),
(155, 'Kitchen/cooking', 'Kitchen/cooking'),
(156, 'Pet supplies', 'Pet supplies'),
(157, 'Tv/movie award', 'Tv/movie award'),
(158, 'Bags/luggage', 'Bags/luggage'),
(159, 'Transport/freight', 'Transport/freight'),
(160, 'Aerospace/defense', 'Aerospace/defense'),
(161, 'Sports venue', 'Sports venue'),
(162, 'Commercial equipment', 'Commercial equipment'),
(163, 'Baby goods/kids goods', 'Baby goods/kids goods'),
(164, 'Bank/financial services', 'Bank/financial services'),
(165, 'Playlist', 'Playlist'),
(166, 'Hospital/clinic', 'Hospital/clinic'),
(167, 'Drugs', 'Drugs'),
(168, 'News personality', 'News personality'),
(169, 'Jewelry/watches', 'Jewelry/watches'),
(170, 'Automobiles and parts', 'Automobiles and parts'),
(171, 'Tv genre', 'Tv genre'),
(172, 'Article', 'Article'),
(173, 'Farming/agriculture', 'Farming/agriculture'),
(174, 'Engineering/construction', 'Engineering/construction'),
(175, 'Music award', 'Music award'),
(176, 'Language', 'Language'),
(177, 'Doctor', 'Doctor'),
(178, 'Lawyer', 'Lawyer'),
(179, 'Country', 'Country'),
(180, 'Profile', 'Profile'),
(181, 'Drink', 'Drink'),
(182, 'Political ideology', 'Political ideology'),
(183, 'Government', 'Government'),
(184, 'Medical procedure', 'Medical procedure'),
(185, 'Product type', 'Product type'),
(186, 'Office supplies', 'Office supplies'),
(187, 'Regional', 'Regional'),
(188, 'Work project', 'Work project'),
(189, 'Industrials', 'Industrials'),
(190, 'Chemicals', 'Chemicals'),
(191, 'Patio/garden', 'Patio/garden'),
(192, 'Mining/materials', 'Mining/materials'),
(193, 'Course', 'Course'),
(194, 'Biotechnology', 'Biotechnology'),
(195, 'Color', 'Color'),
(196, 'Energy/utility', 'Energy/utility'),
(197, 'Train station', 'Train station'),
(198, 'Transit stop', 'Transit stop'),
(199, 'Concentration or major', 'Concentration or major'),
(200, 'Topic', 'Topic'),
(201, 'Building materials', 'Building materials'),
(202, 'Brand/company type', 'Brand/company type'),
(203, 'State/province/region', 'State/province/region'),
(204, 'App page', 'App page'),
(205, 'Degree', 'Degree');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
