SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

INSERT INTO `categories` (`categoryId`, `facebookName`, `prettyName`, `hasOrDoes`, `verb`) VALUES
(1, 'Musician/band', 'bands', 'does', 'listen to'),
(2, 'Movie', 'movies', 'has', 'seen'),
(3, 'Tv show', 'TV shows', 'does', 'watch'),
(4, 'Professional sports team', 'professional sports teams', 'does', 'follow'),
(5, 'Interest', 'interests', 'does', 'have'),
(6, 'Fictional character', 'fictional characters', 'does', 'like'),
(7, 'School', 'schools', 'does', 'like'),
(8, 'Concert tour', 'concert tours', 'has', 'seen'),
(9, 'Entertainment', 'entertainment items', 'does', 'like'),
(10, 'University', 'universities', 'does', 'like'),
(11, 'Movie general', 'movies', 'has', 'seen'),
(12, 'Book', 'books', 'has', 'read'),
(13, 'Field of study', 'fields of study', 'does', 'like'),
(14, 'Organization', 'organizations', 'does', 'like'),
(15, 'Community', 'communities', 'does', 'like'),
(16, 'Author', 'authors', 'does', 'like'),
(17, 'Concert venue', 'concert venues', 'has', 'been to'),
(18, 'Software', 'software', 'does', 'use'),
(19, 'Entertainer', 'entertainers', 'does', 'like'),
(20, 'Wine/spirits', 'wine or spirits', 'does', 'drink'),
(21, 'Public figure', 'public figures', 'does', 'look up to'),
(22, 'Shopping/retail', 'stores', 'does', 'shop at'),
(23, 'Bar', 'bars', 'does', 'go to'),
(24, 'Education', 'education items', 'does', 'like'),
(25, 'Product/service', 'products or services', 'does', 'like'),
(26, 'Company', 'companies', 'does', 'like'),
(27, 'Sports league', 'sports leagues', 'does', 'follow'),
(28, 'Restaurant/cafe', 'restaurants or cafes', 'does', 'eat at'),
(29, 'Sport', 'sports', 'does', 'follow'),
(30, 'Computers/technology', 'computers or technology', 'does', 'like'),
(31, 'Computers', 'computers', 'does', 'like'),
(32, 'Professional services', 'professional services', 'does', 'like'),
(33, 'Games/toys', 'games or toys', 'does', 'play'),
(34, 'Attractions/things to do', 'attractions', 'has', 'seen'),
(35, 'Local business', 'local businesses', 'does', 'like'),
(36, 'Website', 'websites', 'does', 'use'),
(37, 'Food/beverages', 'food or beverages', 'does', 'consume'),
(38, 'Non-profit organization', 'non-profit organizations', 'does', 'like'),
(39, 'Food/grocery', 'food or groceries', 'does', 'like'),
(40, 'Sports/recreation/activities', 'sports or activities', 'does', 'like'),
(41, 'Cause', 'causes', 'does', 'support'),
(42, 'Application', 'applications', 'does', 'like'),
(43, 'Dancer', 'dancers', 'does', 'like'),
(44, 'Retail and consumer merchandise', 'merchandise', 'does', 'like'),
(45, 'Music', 'music items', 'does', 'listen to'),
(46, 'Outdoor gear/sporting goods', 'sporting goods', 'does', 'like'),
(47, 'Athlete', 'athletes', 'does', 'follow'),
(48, 'Comedian', 'comedians', 'does', 'laugh at'),
(49, 'Album', 'albums', 'does', 'listen to'),
(50, 'Actor/director', 'actors', 'does', 'watch'),
(51, 'School sports team', 'school sports teams', 'does', 'follow'),
(52, 'Real estate', 'real estate', 'does', 'like'),
(53, 'Radio station', 'radio stations', 'does', 'listen to'),
(54, 'Clothing', 'clothes', 'does', 'wear'),
(55, 'Political organization', 'political organizations', 'does', 'support'),
(56, 'Movies/music', 'movies/music', 'does', 'enjoy'),
(57, 'Health/medical/pharmaceuticals', 'health/medical/pharmaceuticals', 'does', 'like'),
(58, 'Health/wellness', 'health/wellness items', 'does', 'like'),
(59, 'Politician', 'politicians', 'does', 'support'),
(60, 'Arts/entertainment/nightlife', 'arts/entertainment/nightlife', 'does', 'like'),
(61, 'Small business', 'small businesses', 'does', 'like'),
(62, 'Internet/software', 'internet/software items', 'does', 'like'),
(63, 'Pet services', 'pet services', 'does', 'like'),
(64, 'Event planning/event services', 'event services', 'does', 'like'),
(65, 'Insurance company', 'insurance companies', 'does', 'have'),
(66, 'News/media', 'news or media', 'does', 'use'),
(67, 'App', 'apps', 'does', 'use'),
(68, 'Arts/humanities', 'arts', 'does', 'enjoy'),
(69, 'Artist', 'artists', 'does', 'enjoy'),
(70, 'Personal blog', 'personal blogs', 'does', 'read'),
(71, 'Landmark', 'landmarks', 'has', 'been to'),
(72, 'Diseases', 'diseases', 'does', 'have'),
(73, 'Health/medical/pharmacy', 'health/medical/pharmacy items', 'does', 'like'),
(74, 'Journalist', 'journalists', 'does', 'follow'),
(75, 'Camera/photo', 'camera/photo items', 'does', 'like'),
(76, 'Government official', 'government officials', 'does', 'like'),
(77, 'Household supplies', 'household supplies', 'does', 'use'),
(78, 'Museum/art gallery', 'museums or art galleries', 'has', 'been to'),
(79, 'Producer', 'producers', 'does', 'like'),
(80, 'Computers/internet', 'computer/internet items', 'does', 'like'),
(81, 'Travel/leisure', 'travel/leisure items', 'does', 'like'),
(82, 'Club', 'clubs', 'is', 'in'),
(83, 'Media/news/publishing', 'media/news/publishing items', 'does', 'like'),
(84, 'Teacher', 'teachers', 'did', 'have'),
(85, 'Writer', 'writers', 'does', 'read'),
(86, 'Tv', 'TV items', 'does', 'like'),
(87, 'Appliances', 'appliances', 'does', 'own'),
(88, 'Reference', 'references', 'does', 'like'),
(89, 'Hotel', 'hotels', 'has', 'stayed at'),
(90, 'Record label', 'record labels', 'does', 'like'),
(91, 'Government organization', 'government organization', 'does', 'like'),
(92, 'Tv network', 'TV networks', 'does', 'watch'),
(93, 'Church/religious organization', 'churches or religious organizations', 'does', 'follow'),
(94, 'Consulting/business services', 'consulting/business services', 'does', 'like'),
(95, 'Song', 'songs', 'does', 'listen to'),
(96, 'Society/culture', 'societies or cultures', 'does', 'like'),
(97, 'Business person', 'business people', 'does', 'look up to'),
(98, 'Tv channel', 'TV channel', 'does', 'watch'),
(99, 'Cars', 'cars', 'does', 'like'),
(100, 'Magazine', 'magazines', 'does', 'read'),
(101, 'Local/travel', 'local/travel', 'does', 'like'),
(102, 'Animal', 'animals', 'does', 'like'),
(103, 'Telecommunication', 'telecommunication items', 'does', 'like'),
(104, 'Movie genre', 'movie genres', 'does', 'like'),
(105, 'Musical genre', 'musical genres', 'does', 'like'),
(106, 'Musical instrument', 'musical instruments', 'does', 'play'),
(107, 'Coach', 'coaches', 'does', 'like'),
(108, 'Recreation/sports', 'recreation/sports', 'does', 'like'),
(109, 'Business services', 'business services', 'does', 'like'),
(110, 'Unknown', 'items', 'does', 'like'),
(111, 'Home decor', 'home decor items', 'does', 'like'),
(112, 'Home improvement', 'home improvement items', 'does', 'like'),
(113, 'City', 'cities', 'does', 'like'),
(114, 'Book store', 'book stores', 'does', 'like'),
(115, 'Video', 'videos', 'has', 'seen'),
(116, 'Automotive', 'automotive items', 'does', 'like'),
(117, 'Health/beauty', 'health or beauty items', 'does', 'like'),
(118, 'Bank/financial institution', 'banks or financial institutions', 'does', 'like'),
(119, 'Studio', 'studios', 'does', 'like'),
(120, 'Religion', 'religions', 'does', 'believe in'),
(121, 'Music chart', 'music charts', 'does', 'like'),
(122, 'Public places', 'public places', 'has', 'been to'),
(123, 'Community/government', 'communities or governments', 'does', 'like'),
(124, 'Legal/law', 'legal/law items', 'does', 'like'),
(125, 'Book genre', 'book genres', 'does', 'like'),
(126, 'Animal breed', 'animal breeds', 'does', 'like'),
(127, 'Episode', 'episodes', 'has', 'seen'),
(128, 'Community organization', 'community organizations', 'does', 'like'),
(129, 'Vitamins/supplements', 'vitamins or supplements', 'does', 'take'),
(130, 'Food', 'food items', 'does', 'eat'),
(131, 'Movie theater', 'movie theater', 'has', 'been to'),
(132, 'Furniture', 'furniture', 'does', 'like'),
(133, 'Political party', 'political parties', 'does', 'support'),
(134, 'Work position', 'work positions', 'does', 'like'),
(135, 'Spas/beauty/personal care', 'spas/beauty/personal care items', 'does', 'like'),
(136, 'Business/economy', 'business/economy items', 'does', 'like'),
(137, 'Library', 'libraries', 'does', 'go to'),
(138, 'Home/garden', 'home/garden items', 'does', 'use'),
(139, 'Tours/sightseeing', 'tours/sightseeing', 'does', 'done'),
(140, 'Transportation', 'transportation items', 'does', 'like'),
(141, 'Electronics', 'electronics', 'does', 'like'),
(142, 'Music video', 'music videos', 'has', 'seen'),
(143, 'Airport', 'airports', 'has', 'been to'),
(144, '', '', 'does', 'like'),
(145, 'Science', 'science items', 'does', 'like'),
(146, 'Chef', 'chefs', 'does', 'like'),
(147, 'Non-governmental organization (ngo)', 'non-governmental organizations (ngos)', 'does', 'like'),
(148, 'Publisher', 'publishers', 'does', 'like'),
(149, 'Personal website', 'personal websites', 'does', 'visit'),
(150, 'Tools/equipment', 'tools or equipment', 'does', 'like'),
(151, 'Editor', 'editors', 'does', 'like'),
(152, 'Monarch', 'monarchs', 'does', 'like'),
(153, 'Teens/kids', 'teens/kids items', 'does', 'like'),
(154, 'Amateur sports team', 'amateur sports teams', 'does', 'follow'),
(155, 'Kitchen/cooking', 'kitchen/cooking items', 'does', 'like'),
(156, 'Pet supplies', 'pet supplies', 'does', 'like'),
(157, 'Tv/movie award', 'TV or movie awards', 'does', 'like'),
(158, 'Bags/luggage', 'bags or luggage', 'does', 'like'),
(159, 'Transport/freight', 'transport/freight items', 'does', 'like'),
(160, 'Aerospace/defense', 'aerospace/defense items', 'does', 'like'),
(161, 'Sports venue', 'sports venues', 'has', 'been to'),
(162, 'Commercial equipment', 'commercial equipment', 'does', 'like'),
(163, 'Baby goods/kids goods', 'baby goods/kids goods', 'does', 'like'),
(164, 'Bank/financial services', 'banks or financial services', 'does', 'use'),
(165, 'Playlist', 'playlists', 'does', 'listen to'),
(166, 'Hospital/clinic', 'hospitals or clinics', 'does', 'like'),
(167, 'Drugs', 'drugs', 'does', 'like'),
(168, 'News personality', 'news personalities', 'does', 'like'),
(169, 'Jewelry/watches', 'jewelry or watches', 'does', 'like'),
(170, 'Automobiles and parts', 'automobiles and parts', 'does', 'like'),
(171, 'Tv genre', 'TV genres', 'does', 'like'),
(172, 'Article', 'articles', 'has', 'read'),
(173, 'Farming/agriculture', 'farming/agriculture items', 'does', 'like'),
(174, 'Engineering/construction', 'engineering/construction items', 'does', 'like'),
(175, 'Music award', 'music awards', 'does', 'like'),
(176, 'Language', 'languages', 'does', 'speak'),
(177, 'Doctor', 'doctors', 'does', 'like'),
(178, 'Lawyer', 'lawyer', 'does', 'like'),
(179, 'Country', 'countries', 'does', 'like'),
(180, 'Profile', 'profiles', 'does', 'like'),
(181, 'Drink', 'drinks', 'does', 'drink'),
(182, 'Political ideology', 'political ideologies', 'does', 'support'),
(183, 'Government', 'governments', 'does', 'like'),
(184, 'Medical procedure', 'medical procedures', 'does', 'like'),
(185, 'Product type', 'product types', 'does', 'like'),
(186, 'Office supplies', 'office supplies', 'does', 'like'),
(187, 'Regional', 'regional items', 'does', 'like'),
(188, 'Work project', 'work projects', 'does', 'like'),
(189, 'Industrials', 'industrials', 'does', 'like'),
(190, 'Chemicals', 'chemicals', 'does', 'like'),
(191, 'Patio/garden', 'patio or garden items', 'does', 'like'),
(192, 'Mining/materials', 'mining/materials items', 'does', 'like'),
(193, 'Course', 'courses', 'has', 'taken'),
(194, 'Biotechnology', 'biotechnology items', 'does', 'like'),
(195, 'Color', 'colors', 'does', 'like'),
(196, 'Energy/utility', 'energy/utility items', 'does', 'like'),
(197, 'Train station', 'train stations', 'has', 'been to'),
(198, 'Transit stop', 'transit stops', 'has', 'been to'),
(199, 'Concentration or major', 'concentrations or majors', 'has', 'focused on'),
(200, 'Topic', 'topics', 'is', 'interested in'),
(201, 'Building materials', 'building materials', 'does', 'like'),
(202, 'Brand/company type', 'brand/company type item', 'does', 'like'),
(203, 'State/province/region', 'states/provinces/regions', 'has', 'been to'),
(204, 'App page', 'app pages', 'does', 'like'),
(205, 'Degree', 'degrees', 'has', 'majored in');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
